server:
  port: 8002
  error:
    include-message: always

spring.data.mongodb:
  host: localhost
  port: 27017
  database: recommendation-db

logging:
  level:
    root: INFO
    se.magnus.microservices: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG

---

spring:
  profiles: docker

spring.data.mongodb:
  host: mongodb

server:
  port: 8080