server:
  port: 8001
  error:
    include-message: always

spring.application.name: product

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5

spring.data.mongodb:
  host: localhost
  port: 27017
  database: product-db

spring.cloud.stream:
  defaultBinder: rabbit
  default.contentType: application/json
  bindings.input:
    destination: products
    group: productsGroup

spring.cloud.stream.bindings.input.consumer:
  maxAttempts: 3
  backOffInitialInterval: 500
  backOffMaxInterval: 1000
  backOffMultiplier: 2.0

spring.cloud.stream.rabbit.bindings.input.consumer:
  autoBindDlq: true
  republishToDlq: true

spring.cloud.stream.kafka.bindings.input.consumer:
  enableDlq: true

spring.cloud.stream.kafka.binder:
  brokers: localhost
  defaultBrokerPort: 9092

spring.rebbitmq:
  host: localhost
  port: 5672
  username: guest
  password: guest

logging:
  level:
    root: INFO
    se.magnu: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG

management.endpoint.health.show-details: "ALWAYS"
management.endpoints.web.exposure.include: "*"

---

spring:
  profiles: docker

  data:
    mongodb:
      host: mongodb

  rabbitmq:
    host: rabbitmq

  cloud.stream.kafka.binder.brokers: kafka

server:
  port: 8080

eureka.client.serviceUrl.defaultZone: http://eureka:8761/eureka/